"""add_deleted_at_to_workspace_members

Revision ID: 8d8c130f5700
Revises: a6116932e4b7
Create Date: 2026-07-24 16:42:38.479549

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8d8c130f5700'
down_revision: str | Sequence[str] | None = 'a6116932e4b7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'workspace_members',
        sa.Column(
            'deleted_at',
            sa.DateTime(timezone=True),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_members', 'deleted_at')
    # ### end Alembic commands ###
